blockExoticSubdeps: true
minimumReleaseAge: 10080
trustPolicy: no-downgrade
trustPolicyExclude:
  - "semver@6.3.1"
  - "netlify-cli@26.0.2"
  - "@netlify/zip-it-and-ship-it@14.5.6"
  - "chokidar@4.0.3"
  - "@netlify/edge-bundler@14.10.2"
  - "@netlify/serverless-functions-api@2.15.1"
